apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-58291-20251114000002
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:357609cebb9ed62d70e8adcde08794dda70e7088a1108425ff4a3d31cfcd4109
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-96409-20251113234405
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:21fde844856a542a6a21206bee9285b09cfa150332432d95fc03cfbd6e3b3d4a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-58291-20251114000002
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:357609cebb9ed62d70e8adcde08794dda70e7088a1108425ff4a3d31cfcd4109
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-96409-20251113234405
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:21fde844856a542a6a21206bee9285b09cfa150332432d95fc03cfbd6e3b3d4a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-58291-20251114000002
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:357609cebb9ed62d70e8adcde08794dda70e7088a1108425ff4a3d31cfcd4109
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-96409-20251113234405
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:21fde844856a542a6a21206bee9285b09cfa150332432d95fc03cfbd6e3b3d4a
