apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-95878-20251118000242
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:e8e7f87b8d5da84e684a76a17f8fb48f12da8aefdd1ccc6582d5c6cec87e69b2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-59794-20251117234739
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:3db4cdc84d52b0132875976c3bcd190947bd598284fc91b2d40857d96f9a7c60
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-95878-20251118000242
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:e8e7f87b8d5da84e684a76a17f8fb48f12da8aefdd1ccc6582d5c6cec87e69b2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-59794-20251117234739
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:3db4cdc84d52b0132875976c3bcd190947bd598284fc91b2d40857d96f9a7c60
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-95878-20251118000242
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:e8e7f87b8d5da84e684a76a17f8fb48f12da8aefdd1ccc6582d5c6cec87e69b2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-59794-20251117234739
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:3db4cdc84d52b0132875976c3bcd190947bd598284fc91b2d40857d96f9a7c60
