apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 7.12.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.0-9
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:40920687402fd747ca02d384e63692a5e1db625723a2bf3056a607c92ee8eee1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.0-9
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:d42d713da0ce6806fdc6492b6342586783e6865a82a8647d3c4288439b1751ee
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.0-9
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:40920687402fd747ca02d384e63692a5e1db625723a2bf3056a607c92ee8eee1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.0-9
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:d42d713da0ce6806fdc6492b6342586783e6865a82a8647d3c4288439b1751ee
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.0-9
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:40920687402fd747ca02d384e63692a5e1db625723a2bf3056a607c92ee8eee1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.0-9
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:d42d713da0ce6806fdc6492b6342586783e6865a82a8647d3c4288439b1751ee

        # 7.12.1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7121
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.1-3.1724187703
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b2402179b1d0ff9c950defe5d8808195ef9a4c3e13e3c469cae31ab51d5f5014
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7121
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.1-3.1724186872
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:47fd4ce2533496828aba37bd1f9715e2164d5c90bd0fc6b25e7e0786d723bf01
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7121_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.1-3.1724187703
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b2402179b1d0ff9c950defe5d8808195ef9a4c3e13e3c469cae31ab51d5f5014
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7121_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.1-3.1724186872
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:47fd4ce2533496828aba37bd1f9715e2164d5c90bd0fc6b25e7e0786d723bf01
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7121_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.1-3.1724187703
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b2402179b1d0ff9c950defe5d8808195ef9a4c3e13e3c469cae31ab51d5f5014
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7121_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.1-3.1724186872
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:47fd4ce2533496828aba37bd1f9715e2164d5c90bd0fc6b25e7e0786d723bf01

        # 7.12.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7122
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.2-1
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:7f9b921d89b6d4d91b365659afff127d99f1455b94b48a10a6a7f4c38dd8b700
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7122
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.2-1
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:dc13871dfed52402c40fd192900fc3cb5a49da4fa08e4ec4d0e23a879e83db25
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7122_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.2-1
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:7f9b921d89b6d4d91b365659afff127d99f1455b94b48a10a6a7f4c38dd8b700
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7122_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.2-1
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:dc13871dfed52402c40fd192900fc3cb5a49da4fa08e4ec4d0e23a879e83db25
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7122_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.2-1
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:7f9b921d89b6d4d91b365659afff127d99f1455b94b48a10a6a7f4c38dd8b700
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7122_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.2-1
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:dc13871dfed52402c40fd192900fc3cb5a49da4fa08e4ec4d0e23a879e83db25

        # 7.12.3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7123
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.3-1.1743448396
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9cc48eecf1442ae04b8543fa5d4381a13bc2831390850828834d387006d1342b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7123
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.3-1.1743447390
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:bb6fbd68475a7852b4d99eea6c4ab313f9267da7963162f0d75375d7063409e7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7123_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.3-1.1743448396
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9cc48eecf1442ae04b8543fa5d4381a13bc2831390850828834d387006d1342b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7123_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.3-1.1743447390
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:bb6fbd68475a7852b4d99eea6c4ab313f9267da7963162f0d75375d7063409e7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7123_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.3-1.1743448396
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9cc48eecf1442ae04b8543fa5d4381a13bc2831390850828834d387006d1342b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7123_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.3-1.1743447390
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:bb6fbd68475a7852b4d99eea6c4ab313f9267da7963162f0d75375d7063409e7

        # 7.13.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7130
          #value: registry.redhat.io/amq7/amq-broker-init-rhel9:7.13.0-3.1751409429
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:ff80e0a7accda6825bf834d9aec27f48205dd6329991890dd017b4d21d0da5c8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7130
          #value: registry.redhat.io/amq7/amq-broker-rhel9:7.13.0-4.1751408443
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:755d0f7421efba76f52818bb3a8667cd7d2dcff2c7054dac1a4637b74ecac51d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7130_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel9:7.13.0-3.1751409429
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:ff80e0a7accda6825bf834d9aec27f48205dd6329991890dd017b4d21d0da5c8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7130_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel9:7.13.0-4.1751408443
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:755d0f7421efba76f52818bb3a8667cd7d2dcff2c7054dac1a4637b74ecac51d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7130_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel9:7.13.0-3.1751409429
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:ff80e0a7accda6825bf834d9aec27f48205dd6329991890dd017b4d21d0da5c8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7130_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel9:7.13.0-4.1751408443
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:755d0f7421efba76f52818bb3a8667cd7d2dcff2c7054dac1a4637b74ecac51d

        # 7.12.4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7124
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.4-5.1751406286
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:ffffa9875f0379e9373f89f05eb06e5a193273bb04bc3aa5f85b044357b79098
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7124
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.4-3.1751404800
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:16253895bc113f395dc6ab5cd511901e43b6ee676369ec80d598a8741c3c9bf4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7124_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.4-5.1751406286
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:ffffa9875f0379e9373f89f05eb06e5a193273bb04bc3aa5f85b044357b79098
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7124_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.4-3.1751404800
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:16253895bc113f395dc6ab5cd511901e43b6ee676369ec80d598a8741c3c9bf4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7124_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.4-5.1751406286
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:ffffa9875f0379e9373f89f05eb06e5a193273bb04bc3aa5f85b044357b79098
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7124_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.4-3.1751404800
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:16253895bc113f395dc6ab5cd511901e43b6ee676369ec80d598a8741c3c9bf4

        # 7.13.1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7131
          #value: registry.redhat.io/amq7/amq-broker-init-rhel9:7.13.1-1.1758136953
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:54004a7076fff8787f14e238a7c2dd21884a882097fb474412d96b0138ca9249
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7131
          #value: registry.redhat.io/amq7/amq-broker-rhel9:7.13.1-1.1758136331
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:c8ccf2fb03e97fcedc3299ada2f63f47beaa7643df4b201fcb30899f923436b9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7131_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel9:7.13.1-1.1758136953
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:54004a7076fff8787f14e238a7c2dd21884a882097fb474412d96b0138ca9249
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7131_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel9:7.13.1-1.1758136331
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:c8ccf2fb03e97fcedc3299ada2f63f47beaa7643df4b201fcb30899f923436b9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7131_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel9:7.13.1-1.1758136953
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:54004a7076fff8787f14e238a7c2dd21884a882097fb474412d96b0138ca9249
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7131_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel9:7.13.1-1.1758136331
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:c8ccf2fb03e97fcedc3299ada2f63f47beaa7643df4b201fcb30899f923436b9

        # 7.12.5
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7125
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.5-2.1764071657
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b3f83d5f406fd902bd9c6773f14c07649474edc4ca40bbcf75142b316a094247
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7125
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.5-2.1764070640
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:81a004dc9d33eec151ae38f2767fe264a590710d2c3a60e934d440587f9980c4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7125_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.5-2.1764071657
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b3f83d5f406fd902bd9c6773f14c07649474edc4ca40bbcf75142b316a094247
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7125_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.5-2.1764070640
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:81a004dc9d33eec151ae38f2767fe264a590710d2c3a60e934d440587f9980c4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7125_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.5-2.1764071657
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b3f83d5f406fd902bd9c6773f14c07649474edc4ca40bbcf75142b316a094247
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7125_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.5-2.1764070640
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:81a004dc9d33eec151ae38f2767fe264a590710d2c3a60e934d440587f9980c4

        # 7.13.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7132
          #value: registry.redhat.io/amq7/amq-broker-init-rhel9:7.13.2-1.1764564389
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:80bca92852d08a7657fb090fe44bfda10baf231c31139a24edec83f542f36232
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7132
          #value: registry.redhat.io/amq7/amq-broker-rhel9:7.13.2-1.1764563720
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:dd84cb2dfdecd4f5a3fc50a9e167ea6970d1d52d8c7427c201a74a76e151d430
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7132_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel9:7.13.2-1.1764564389
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:80bca92852d08a7657fb090fe44bfda10baf231c31139a24edec83f542f36232
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7132_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel9:7.13.2-1.1764563720
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:dd84cb2dfdecd4f5a3fc50a9e167ea6970d1d52d8c7427c201a74a76e151d430
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7132_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel9:7.13.2-1.1764564389
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:80bca92852d08a7657fb090fe44bfda10baf231c31139a24edec83f542f36232
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7132_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel9:7.13.2-1.1764563720
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:dd84cb2dfdecd4f5a3fc50a9e167ea6970d1d52d8c7427c201a74a76e151d430

        # 7.13.3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7133
          #value: registry.redhat.io/amq7/amq-broker-init-rhel9:7.13.3-1
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:e2aa0dce542b287259d0b2a7eac9b32e4909a8b75e85787be9101ff25f2d4cd8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7133
          #value: registry.redhat.io/amq7/amq-broker-rhel9:7.13.3-1
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:f92b41ededb92e88d439caf1fbeb9322354da4b7a298bb4ae6873871a1e3fcad
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7133_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel9:7.13.3-1
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:e2aa0dce542b287259d0b2a7eac9b32e4909a8b75e85787be9101ff25f2d4cd8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7133_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel9:7.13.3-1
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:f92b41ededb92e88d439caf1fbeb9322354da4b7a298bb4ae6873871a1e3fcad
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7133_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel9:7.13.3-1
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:e2aa0dce542b287259d0b2a7eac9b32e4909a8b75e85787be9101ff25f2d4cd8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7133_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel9:7.13.3-1
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:f92b41ededb92e88d439caf1fbeb9322354da4b7a298bb4ae6873871a1e3fcad
