apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-25853-20260205093344
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:0a62619896cbaf7275403b64d968fa76e382bf9051ab29ed98d45988e8df4a97
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-88303-20260205083307
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:2572c5af7dfe69ed7956bf0f87b1ec438b22fde26f84d3d41cc305f3666e0dc6
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-25853-20260205093344
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:0a62619896cbaf7275403b64d968fa76e382bf9051ab29ed98d45988e8df4a97
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-88303-20260205083307
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:2572c5af7dfe69ed7956bf0f87b1ec438b22fde26f84d3d41cc305f3666e0dc6
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-25853-20260205093344
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:0a62619896cbaf7275403b64d968fa76e382bf9051ab29ed98d45988e8df4a97
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-88303-20260205083307
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:2572c5af7dfe69ed7956bf0f87b1ec438b22fde26f84d3d41cc305f3666e0dc6
