apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-21011-20260101011046
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:b93d32ea2e7d582fe83de3e765aea4920d79350b5c6ba77f62862e0b4832b266
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-46405-20260101005708
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:f1c65e6570d38e4878f838d5da04e8ce9f23a1b72dbdc0d9a615efcf1633899a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-21011-20260101011046
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:b93d32ea2e7d582fe83de3e765aea4920d79350b5c6ba77f62862e0b4832b266
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-46405-20260101005708
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:f1c65e6570d38e4878f838d5da04e8ce9f23a1b72dbdc0d9a615efcf1633899a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-21011-20260101011046
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:b93d32ea2e7d582fe83de3e765aea4920d79350b5c6ba77f62862e0b4832b266
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-46405-20260101005708
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:f1c65e6570d38e4878f838d5da04e8ce9f23a1b72dbdc0d9a615efcf1633899a
