apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-98606-20251211000347
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:fc913455e58546a004895cfc80adc79bc2379dd18e27daf94875073fbc57b0d8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-22122-20251210234759
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:3384860d54a1a34744c11a8d1eb4fa722cfe893148743bea1869fa7f8af955ec
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-98606-20251211000347
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:fc913455e58546a004895cfc80adc79bc2379dd18e27daf94875073fbc57b0d8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-22122-20251210234759
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:3384860d54a1a34744c11a8d1eb4fa722cfe893148743bea1869fa7f8af955ec
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-98606-20251211000347
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:fc913455e58546a004895cfc80adc79bc2379dd18e27daf94875073fbc57b0d8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-22122-20251210234759
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:3384860d54a1a34744c11a8d1eb4fa722cfe893148743bea1869fa7f8af955ec
