apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-49031-20260110000952
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:462eb449bfeb3a1f156c971ae1d7cca2a2f6399cc12970b16823d78bdad54095
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-10733-20260109235233
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:2ac3ab8328890016436160696f04c362fc7ac24832ebe7d879ab1b504ce58340
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-49031-20260110000952
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:462eb449bfeb3a1f156c971ae1d7cca2a2f6399cc12970b16823d78bdad54095
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-10733-20260109235233
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:2ac3ab8328890016436160696f04c362fc7ac24832ebe7d879ab1b504ce58340
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-49031-20260110000952
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:462eb449bfeb3a1f156c971ae1d7cca2a2f6399cc12970b16823d78bdad54095
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-10733-20260109235233
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:2ac3ab8328890016436160696f04c362fc7ac24832ebe7d879ab1b504ce58340
