apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-42204-20260111235440
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:9d81cda08b7f1623166476c4577fa29c69044de07aff9a05610bc690bf92dc8e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-58307-20260111234023
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:0550ef339ffcea74eb76f7e8f7227136a59191cf132cf8dbdb010d59085050e2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-42204-20260111235440
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:9d81cda08b7f1623166476c4577fa29c69044de07aff9a05610bc690bf92dc8e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-58307-20260111234023
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:0550ef339ffcea74eb76f7e8f7227136a59191cf132cf8dbdb010d59085050e2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-42204-20260111235440
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:9d81cda08b7f1623166476c4577fa29c69044de07aff9a05610bc690bf92dc8e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-58307-20260111234023
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:0550ef339ffcea74eb76f7e8f7227136a59191cf132cf8dbdb010d59085050e2
