apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-69754-20251127235945
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:fc8a6c29bea96b3f4433de29bfcb91871043851faea4134d35ff6b53fdc91c55
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-53382-20251127234439
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:b9f06fd6f290150aa5be5034aed26ab4f0322617a05043745a680fb8ad44c661
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-69754-20251127235945
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:fc8a6c29bea96b3f4433de29bfcb91871043851faea4134d35ff6b53fdc91c55
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-53382-20251127234439
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:b9f06fd6f290150aa5be5034aed26ab4f0322617a05043745a680fb8ad44c661
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-69754-20251127235945
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:fc8a6c29bea96b3f4433de29bfcb91871043851faea4134d35ff6b53fdc91c55
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-53382-20251127234439
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:b9f06fd6f290150aa5be5034aed26ab4f0322617a05043745a680fb8ad44c661
