apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-51340-20260221001951
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:de3f11793d509a7f69d0466c7f058b0bdfe09e28422d0380c87e4f4b64a502ea
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-27830-20260221000635
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:080ce9290e91f0c8802a8d04a04fb3a9513728d578f1857b7f16691c07c54e6c
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-51340-20260221001951
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:de3f11793d509a7f69d0466c7f058b0bdfe09e28422d0380c87e4f4b64a502ea
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-27830-20260221000635
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:080ce9290e91f0c8802a8d04a04fb3a9513728d578f1857b7f16691c07c54e6c
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-51340-20260221001951
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:de3f11793d509a7f69d0466c7f058b0bdfe09e28422d0380c87e4f4b64a502ea
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-27830-20260221000635
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:080ce9290e91f0c8802a8d04a04fb3a9513728d578f1857b7f16691c07c54e6c
