apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-74384-20251209000127
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:38f71ab3c7fb38d8689d76b580aea588833a8df8b44b38732204df0752e9fc0c
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-30515-20251208234842
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:e014b3b1078c9365ad83eb4cb955bce5a114184c6db0a436fc78f5fb8988c088
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-74384-20251209000127
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:38f71ab3c7fb38d8689d76b580aea588833a8df8b44b38732204df0752e9fc0c
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-30515-20251208234842
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:e014b3b1078c9365ad83eb4cb955bce5a114184c6db0a436fc78f5fb8988c088
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-74384-20251209000127
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:38f71ab3c7fb38d8689d76b580aea588833a8df8b44b38732204df0752e9fc0c
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-30515-20251208234842
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:e014b3b1078c9365ad83eb4cb955bce5a114184c6db0a436fc78f5fb8988c088
