apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-18423-20260216115211
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:e43f4da844b4c0b0a9962e3dc3fb2cb6989e17d189f289c6aa663e6659b614b5
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-68299-20260216113710
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:b81314e41f400d877c13c3ea9555a07a12ee21751a0c29d7f8c70e5334e23772
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-18423-20260216115211
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:e43f4da844b4c0b0a9962e3dc3fb2cb6989e17d189f289c6aa663e6659b614b5
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-68299-20260216113710
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:b81314e41f400d877c13c3ea9555a07a12ee21751a0c29d7f8c70e5334e23772
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-18423-20260216115211
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:e43f4da844b4c0b0a9962e3dc3fb2cb6989e17d189f289c6aa663e6659b614b5
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-68299-20260216113710
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:b81314e41f400d877c13c3ea9555a07a12ee21751a0c29d7f8c70e5334e23772
