apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-99166-20260114160010
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:1d5b1b60ae2bff0dadd3d202d2df364969898b517c5df94894e3b0296e6fdf4d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-69150-20260114154422
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:07c71271c389cf1a796ae14803272de87f84303fedca5bc598b301b830d5edc3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-99166-20260114160010
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:1d5b1b60ae2bff0dadd3d202d2df364969898b517c5df94894e3b0296e6fdf4d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-69150-20260114154422
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:07c71271c389cf1a796ae14803272de87f84303fedca5bc598b301b830d5edc3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-99166-20260114160010
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:1d5b1b60ae2bff0dadd3d202d2df364969898b517c5df94894e3b0296e6fdf4d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-69150-20260114154422
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:07c71271c389cf1a796ae14803272de87f84303fedca5bc598b301b830d5edc3
