apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-41869-20260108235903
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:90a53b750a44b7761527837c26169dc330e41de47186321eab5ac0a3c6ca034f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-16377-20260108234443
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:649e5cabf762313c93803cbf314f0213f934bb13194cc36273814e3058eebca0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-41869-20260108235903
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:90a53b750a44b7761527837c26169dc330e41de47186321eab5ac0a3c6ca034f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-16377-20260108234443
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:649e5cabf762313c93803cbf314f0213f934bb13194cc36273814e3058eebca0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-41869-20260108235903
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:90a53b750a44b7761527837c26169dc330e41de47186321eab5ac0a3c6ca034f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-16377-20260108234443
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:649e5cabf762313c93803cbf314f0213f934bb13194cc36273814e3058eebca0
