apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    metadata:
      labels:
        com.company: Red_Hat
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: 2025.Q4
        rht.comp: Broker_AMQ
        rht.comp_ver: 7.13.3
        rht.subcomp: broker-amq-operator
        rht.subcomp_t: application
