apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-65871-20251227235602
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:14e687e74ea90415bec24c3a0424198517bc2a59a5ee883218dbf6cab685bb69
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-73083-20251227234227
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:4ea4dd7d82e43ae2d96e81b8af3e297eab42ce0ab86f59f9b49e3a2b84dd1026
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-65871-20251227235602
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:14e687e74ea90415bec24c3a0424198517bc2a59a5ee883218dbf6cab685bb69
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-73083-20251227234227
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:4ea4dd7d82e43ae2d96e81b8af3e297eab42ce0ab86f59f9b49e3a2b84dd1026
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-65871-20251227235602
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:14e687e74ea90415bec24c3a0424198517bc2a59a5ee883218dbf6cab685bb69
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-73083-20251227234227
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:4ea4dd7d82e43ae2d96e81b8af3e297eab42ce0ab86f59f9b49e3a2b84dd1026
