apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-44726-20260220070730
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:73cde4a7489e819ee40e58a6ee40c0e81ce8dda4e82a713f6565fca4c552b98c
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-53704-20260220065229
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:bd534a9e3804ce5a8b565d5889a16f20decaf447565915641c8e98b7e3f9b955
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-44726-20260220070730
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:73cde4a7489e819ee40e58a6ee40c0e81ce8dda4e82a713f6565fca4c552b98c
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-53704-20260220065229
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:bd534a9e3804ce5a8b565d5889a16f20decaf447565915641c8e98b7e3f9b955
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-44726-20260220070730
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:73cde4a7489e819ee40e58a6ee40c0e81ce8dda4e82a713f6565fca4c552b98c
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-53704-20260220065229
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:bd534a9e3804ce5a8b565d5889a16f20decaf447565915641c8e98b7e3f9b955
