apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-98075-20260207235712
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:96a1254c25474789d27c6d3593dc38c8c6634f871ca5c3fbfa6388091cefb37d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-10258-20260207234339
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:18511f9760184778c2089b9fef9ae52fefef13a78f0ce074679fe5fa375686a4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-98075-20260207235712
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:96a1254c25474789d27c6d3593dc38c8c6634f871ca5c3fbfa6388091cefb37d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-10258-20260207234339
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:18511f9760184778c2089b9fef9ae52fefef13a78f0ce074679fe5fa375686a4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-98075-20260207235712
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:96a1254c25474789d27c6d3593dc38c8c6634f871ca5c3fbfa6388091cefb37d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-10258-20260207234339
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:18511f9760184778c2089b9fef9ae52fefef13a78f0ce074679fe5fa375686a4
