apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 7.11.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7110
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.0-7.1687445595
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b9f93c243ead118651083880786a81c624f390fcc3596c7ec5ebd55f34f95ea3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7110
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.0-8
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:25c3732e945b4bc3e9aca721ce709d0217339b065d9dac9afdb6202e9fd8a799
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7110_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.0-7.1687445595
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b9f93c243ead118651083880786a81c624f390fcc3596c7ec5ebd55f34f95ea3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7110_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.0-8
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:25c3732e945b4bc3e9aca721ce709d0217339b065d9dac9afdb6202e9fd8a799
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7110_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.0-7.1687445595
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b9f93c243ead118651083880786a81c624f390fcc3596c7ec5ebd55f34f95ea3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7110_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.0-8
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:25c3732e945b4bc3e9aca721ce709d0217339b065d9dac9afdb6202e9fd8a799

        # 7.11.1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7111
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.1-2.1693372837
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9c1ac38bf8eec67a3da57c3cc61105513776a749408cb287fe6448a17889de4e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7111
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.1-2.1693371471
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:40ccaf2bb2e0f8132f2541b39cb835f17b38050b3ca9232f0861fd5fcaf4324a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7111_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.1-2.1693372837
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9c1ac38bf8eec67a3da57c3cc61105513776a749408cb287fe6448a17889de4e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7111_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.1-2.1693371471
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:40ccaf2bb2e0f8132f2541b39cb835f17b38050b3ca9232f0861fd5fcaf4324a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7111_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.1-2.1693372837
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9c1ac38bf8eec67a3da57c3cc61105513776a749408cb287fe6448a17889de4e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7111_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.1-2.1693371471
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:40ccaf2bb2e0f8132f2541b39cb835f17b38050b3ca9232f0861fd5fcaf4324a

        # 7.11.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7112
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.2-4.1697654363
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:0dde839c2dce7cb684094bf26523c8e16677de03149a0fff468b8c3f106e1f4f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7112
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.2-5.1697648860
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:29f07006ad62023c20d34971cb3ae900349efae5ab2918aaa8e5647d788032be
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7112_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.2-4.1697654363
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:0dde839c2dce7cb684094bf26523c8e16677de03149a0fff468b8c3f106e1f4f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7112_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.2-5.1697648860
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:29f07006ad62023c20d34971cb3ae900349efae5ab2918aaa8e5647d788032be
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7112_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.2-4.1697654363
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:0dde839c2dce7cb684094bf26523c8e16677de03149a0fff468b8c3f106e1f4f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7112_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.2-5.1697648860
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:29f07006ad62023c20d34971cb3ae900349efae5ab2918aaa8e5647d788032be

        # 7.11.3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7113
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.3-1.1698107486
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5e5d8b551ab8ca377e0bc939037970a2f31ee14e9f555853ebea2759d673895a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7113
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.3-1.1698106824
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ade37271426ab8f543d72f8da3e9f663d665f9427379a2539fc9323f6897cc44
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7113_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.3-1.1698107486
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5e5d8b551ab8ca377e0bc939037970a2f31ee14e9f555853ebea2759d673895a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7113_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.3-1.1698106824
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ade37271426ab8f543d72f8da3e9f663d665f9427379a2539fc9323f6897cc44
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7113_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.3-1.1698107486
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5e5d8b551ab8ca377e0bc939037970a2f31ee14e9f555853ebea2759d673895a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7113_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.3-1.1698106824
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ade37271426ab8f543d72f8da3e9f663d665f9427379a2539fc9323f6897cc44

        # 7.11.4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7114
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.4-1
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8b4c4400a02c6cacfd978147b158e2ccbe5da955578b4b970a5ee7edac865326
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7114
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.4-1
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:89bb769b4c33eb931cc7866eeabec9a315b913851cfa84bc6e11ae8d1e8b2cbb
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7114_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.4-1
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8b4c4400a02c6cacfd978147b158e2ccbe5da955578b4b970a5ee7edac865326
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7114_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.4-1
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:89bb769b4c33eb931cc7866eeabec9a315b913851cfa84bc6e11ae8d1e8b2cbb
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7114_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.4-1
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8b4c4400a02c6cacfd978147b158e2ccbe5da955578b4b970a5ee7edac865326
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7114_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.4-1
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:89bb769b4c33eb931cc7866eeabec9a315b913851cfa84bc6e11ae8d1e8b2cbb

        # 7.11.5
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7115
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.5-4
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5f842ebe9a6a4294a056ad10189a5f277cfd3fb4e6e0b3225e194bd5c131151d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7115
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.5-6
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:7d53744ae8c77aea09c59165486c9ed0eaa131140f6b346042293bce0bd8a745
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7115_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.5-4
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5f842ebe9a6a4294a056ad10189a5f277cfd3fb4e6e0b3225e194bd5c131151d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7115_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.5-6
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:7d53744ae8c77aea09c59165486c9ed0eaa131140f6b346042293bce0bd8a745
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7115_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.5-4
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5f842ebe9a6a4294a056ad10189a5f277cfd3fb4e6e0b3225e194bd5c131151d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7115_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.5-6
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:7d53744ae8c77aea09c59165486c9ed0eaa131140f6b346042293bce0bd8a745

        # 7.11.6
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7116
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.6-3.1712922470
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:442b6638133d42fa7faa41d86e47be95cdca56c2e16efcd6e7e22991c3812a36
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7116
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.6-4.1712921788
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:0f443f5aa818dd85bfa93e51e37bdac3909628a283aa52a89125b527dd75d9aa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7116_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.6-3.1712922470
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:442b6638133d42fa7faa41d86e47be95cdca56c2e16efcd6e7e22991c3812a36
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7116_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.6-4.1712921788
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:0f443f5aa818dd85bfa93e51e37bdac3909628a283aa52a89125b527dd75d9aa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7116_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.6-3.1712922470
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:442b6638133d42fa7faa41d86e47be95cdca56c2e16efcd6e7e22991c3812a36
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7116_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.6-4.1712921788
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:0f443f5aa818dd85bfa93e51e37bdac3909628a283aa52a89125b527dd75d9aa

        # 7.12.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.0-9
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:40920687402fd747ca02d384e63692a5e1db625723a2bf3056a607c92ee8eee1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.0-9
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:d42d713da0ce6806fdc6492b6342586783e6865a82a8647d3c4288439b1751ee
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.0-9
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:40920687402fd747ca02d384e63692a5e1db625723a2bf3056a607c92ee8eee1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.0-9
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:d42d713da0ce6806fdc6492b6342586783e6865a82a8647d3c4288439b1751ee
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.0-9
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:40920687402fd747ca02d384e63692a5e1db625723a2bf3056a607c92ee8eee1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.0-9
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:d42d713da0ce6806fdc6492b6342586783e6865a82a8647d3c4288439b1751ee

        # 7.11.7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7117
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.7-2.1721235486
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:1a686eb4a11c048a1e43c2a2f1cbeed073fcc622b979c07ab81dbe0d91138bc6
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7117
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.7-2.1721234902
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:170c52f1f2de052f18eb4a5e60b3b44a3641a3f2f6eaea899a2e9ac3bbe8fd0a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7117_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.7-2.1721235486
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:1a686eb4a11c048a1e43c2a2f1cbeed073fcc622b979c07ab81dbe0d91138bc6
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7117_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.7-2.1721234902
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:170c52f1f2de052f18eb4a5e60b3b44a3641a3f2f6eaea899a2e9ac3bbe8fd0a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7117_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.7-2.1721235486
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:1a686eb4a11c048a1e43c2a2f1cbeed073fcc622b979c07ab81dbe0d91138bc6
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7117_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.7-2.1721234902
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:170c52f1f2de052f18eb4a5e60b3b44a3641a3f2f6eaea899a2e9ac3bbe8fd0a

        # 7.12.1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7121
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.1-3.1724041237
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:be975054ea9e2c427fd9612bde17e2897342ad9e285a6bb4d9b604daac7cfaed
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7121
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.1-3.1724040183
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:329f24c48be5d8c626b08c126a8e088ee8887198f0384d66e6ac17aa21ce42cc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7121_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.1-3.1724041237
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:be975054ea9e2c427fd9612bde17e2897342ad9e285a6bb4d9b604daac7cfaed
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7121_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.1-3.1724040183
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:329f24c48be5d8c626b08c126a8e088ee8887198f0384d66e6ac17aa21ce42cc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7121_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.1-3.1724041237
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:be975054ea9e2c427fd9612bde17e2897342ad9e285a6bb4d9b604daac7cfaed
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7121_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.1-3.1724040183
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:329f24c48be5d8c626b08c126a8e088ee8887198f0384d66e6ac17aa21ce42cc

        # 7.12.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7122
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.2-1
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:7f9b921d89b6d4d91b365659afff127d99f1455b94b48a10a6a7f4c38dd8b700
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7122
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.2-1
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:dc13871dfed52402c40fd192900fc3cb5a49da4fa08e4ec4d0e23a879e83db25
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7122_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.2-1
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:7f9b921d89b6d4d91b365659afff127d99f1455b94b48a10a6a7f4c38dd8b700
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7122_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.2-1
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:dc13871dfed52402c40fd192900fc3cb5a49da4fa08e4ec4d0e23a879e83db25
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7122_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.2-1
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:7f9b921d89b6d4d91b365659afff127d99f1455b94b48a10a6a7f4c38dd8b700
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7122_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.2-1
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:dc13871dfed52402c40fd192900fc3cb5a49da4fa08e4ec4d0e23a879e83db25
