apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-95426-20260126121837
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:3db58395a889eb638a5bded2b4c5713f6162e24a64ffe35733a4ce9f60f04fcc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-70206-20260126120249
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:bc97b167e21d47109c5662457bd4b64c63f9eae6bcc7f1396584880165da868e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-95426-20260126121837
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:3db58395a889eb638a5bded2b4c5713f6162e24a64ffe35733a4ce9f60f04fcc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-70206-20260126120249
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:bc97b167e21d47109c5662457bd4b64c63f9eae6bcc7f1396584880165da868e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-95426-20260126121837
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:3db58395a889eb638a5bded2b4c5713f6162e24a64ffe35733a4ce9f60f04fcc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-70206-20260126120249
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:bc97b167e21d47109c5662457bd4b64c63f9eae6bcc7f1396584880165da868e
