apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-92522-20251129235727
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:98c2f819517d52b9d766e13a569364f8da7b9c12517c4a11c7ddbbfd7bf19d0e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-72320-20251129234311
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:86f0b1bd546e3da92b7df99e470eaba7dba3156f649c29ad434c3b4795829e9e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-92522-20251129235727
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:98c2f819517d52b9d766e13a569364f8da7b9c12517c4a11c7ddbbfd7bf19d0e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-72320-20251129234311
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:86f0b1bd546e3da92b7df99e470eaba7dba3156f649c29ad434c3b4795829e9e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-92522-20251129235727
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:98c2f819517d52b9d766e13a569364f8da7b9c12517c4a11c7ddbbfd7bf19d0e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-72320-20251129234311
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:86f0b1bd546e3da92b7df99e470eaba7dba3156f649c29ad434c3b4795829e9e
