apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-88440-20251216235532
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:6c5886aa51981555a1cb063535d94eafb4fc286a0f6383034cc54cee146d9a7a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-61931-20251216234113
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:edfc51c08f82ca79f93c7ced5bd890c8b82ec0688dffda523b61be008962384d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-88440-20251216235532
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:6c5886aa51981555a1cb063535d94eafb4fc286a0f6383034cc54cee146d9a7a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-61931-20251216234113
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:edfc51c08f82ca79f93c7ced5bd890c8b82ec0688dffda523b61be008962384d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-88440-20251216235532
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:6c5886aa51981555a1cb063535d94eafb4fc286a0f6383034cc54cee146d9a7a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-61931-20251216234113
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:edfc51c08f82ca79f93c7ced5bd890c8b82ec0688dffda523b61be008962384d
