apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-19153-20260203001156
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:1c43ea62e9a94b1f531bfcf10ca442690f7b554dd81f6885a947d0af9e5293de
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-64577-20260202235824
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:3e0445e612ffe420ef5687a9bf871cea5443d6639348330d70cd61469d9668da
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-19153-20260203001156
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:1c43ea62e9a94b1f531bfcf10ca442690f7b554dd81f6885a947d0af9e5293de
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-64577-20260202235824
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:3e0445e612ffe420ef5687a9bf871cea5443d6639348330d70cd61469d9668da
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel9:8.0.0-scratch-19153-20260203001156
          value: registry.redhat.io/amq8/amq-broker-init-rhel9@sha256:1c43ea62e9a94b1f531bfcf10ca442690f7b554dd81f6885a947d0af9e5293de
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel9:8.0.0-scratch-64577-20260202235824
          value: registry.redhat.io/amq8/amq-broker-rhel9@sha256:3e0445e612ffe420ef5687a9bf871cea5443d6639348330d70cd61469d9668da
