apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    image: registry.redhat.io/amq7/amq-broker:7.7
    persistenceEnabled: true
    messageMigration: true
