apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 2
    image: registry.redhat.io/amq7/amq-broker:7.7
    persistenceEnabled: true
    messageMigration: true
  acceptors:
  - name: amqp
    protocols: amqp
    port: 5672
    sslEnabled: true
