annotations:
  name: "amq7/amq-broker-rhel8-operator-bundle"
  description: "Red Hat AMQ Broker 8.0 Operator Bundle"
  maintainer: "Roddie Kieley <rkieley@redhat.com>"
  version: "8.0.0"
  summary: "Red Hat AMQ Broker 8.0 Operator Bundle"
  amq.broker.version: "8.0.0.OPR.1.SR1"
  com.redhat.component: "amq-broker-rhel8-operator-bundle-container"
  com.redhat.delivery.backport: false
  com.redhat.delivery.operator.bundle: true
  com.redhat.openshift.versions: "v4.9"
  io.k8s.display-name: "Red Hat AMQ Broker 8.0 Operator Bundle"
  io.openshift.tags: "messaging,amq,integration,operator,golang"
