annotations:
  name: "amq7/amq-broker-rhel8-operator-bundle"
  description: "Red Hat AMQ Broker 7.12 Operator Bundle"
  maintainer: "Roddie Kieley <rkieley@redhat.com>"
  version: "7.12.1"
  summary: "Red Hat AMQ Broker 7.12 Operator Bundle"
  amq.broker.version: "7.12.1.OPR.1.CR3"
  com.redhat.component: "amq-broker-rhel8-operator-bundle-container"
  com.redhat.delivery.backport: false
  com.redhat.delivery.operator.bundle: true
  com.redhat.openshift.versions: "v4.12"
  io.k8s.display-name: "Red Hat AMQ Broker 7.12 Operator Bundle"
  io.openshift.tags: "messaging,amq,integration,operator,golang"
