annotations:
  name: "arkmq-org/activemq-artemis-operator-bundle"
  description: "ArkMQ Broker Operator Bundle"
  maintainer: "ArkMQ <info@arkmq.org>"
  version: "2.1.1"
  com.redhat.openshift.versions: "v4.12"
