apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: activemq-artemis-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      name: activemq-artemis-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        control-plane: controller-manager
        name: activemq-artemis-operator
    spec:
      containers:
      - args:
        - --zap-log-level=info
        - --zap-encoder=console
        - --zap-time-encoding=iso8601
        - --leader-elect
        command:
        - /home/activemq-artemis-operator/bin/entrypoint
        env:
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2150
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:edbec2276270c2f890572daf9141390bc33b5cf75621eca6e10f11bb144944f3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2150
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:39f34248f112751b7835f746016990046d21374a6514cb528632e0b06c76616b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2160
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:4fa0e5420f0f3fc3669b2268de12abcf441e3b70babf07a5fbdac1b946ab33d0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2160
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:005074711b2af77d56309e18e44cd9a7bd7c49b0982ae312d7ca2b120100b351
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2180
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:58b4effb8b83666c59adb657149dc0f037604254b4cd538de0cfaf50f9c14ddd
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2180
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:474de621b3c892a7fdcb992a7c03b496f39f70c78d23f3c9159294e2db7b4bd4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2200
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:b05852acb764caa16bec496eef108f5f9b66d8f300e09a0a267b7eaf4c910596
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2200
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:de52f034dc04bbf1c3a7a68f3ff040d76730bfb64b760c4420526c924613c1a0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2210
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:f63ba7261c3f9b81d3c29251a584a74b153109482753a20a960acf65bd851601
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2210
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:661931ae563086458a15b387e9d7b2561a64b48d4790529f636ed78cf399f579
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2220
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:895512e378006bc519d0b28196f61eabff27c6800e3a2951b21a19ac74cd5579
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2220
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:a34bcbf7585078a178e464f047e2f670eb0217ac66e409b08c4da0594f5907d3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2230
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:c9e0442ed7a2f3d378e52b92b85d6bfbf650896948890ef912e7bedf478fea52
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2230
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:f3e8ebad14c2385e47b260113beb7d6467f834aa04bc37eb12bc9bbc92b7b8b7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2250
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:e2438670831bad39bb08147bbebe67ef9465899fb7750f1a5a185569f99d5fb5
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2250
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:2d155bffd246f26f516a6075ec170babc1373c72bb664cba4e3c58521ffd3558
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2260
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:634f3d8fd620607b56e0360a191d23a9cb8a32ba0ba1f24fe20791ec52343586
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2260
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:f25db980c3229e66cf48690aa175f6f93e3dce3974c0e70ab23af6462e7d1893
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2270
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:9bbb915855f29ea16950a3fd50d0b9bac25f82cba7d197579e04d9c33a5b02c4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2270
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:a4628c2591ec06caf21a3467f6e3faeaede7fa402b4f137d943b25b4dd4ad343
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2271
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:fc9b9a4c7550d84fd90335dd4f9e0d8d39c09136c6034b28490a368368cb11f1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2271
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:2895b2cf6292c951a0cdde78e755514f5d7cb43ce9f7b6e7dc381d8dfeec31ab
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2280
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:264b33a9aad90d32a41258904f35092a141d76dcef0c115d414475444100aace
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2280
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:42230ce9d11a1949a5bb73b6ee218b1581f585bcd553485ee438e1c5b50fcf8b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2290
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:56bae938a6b4cd87f9f5284931f440f9b9d116cda3b63b13f83a4b1c6c641959
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2290
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:4be60cfa2a300b2eef9b5f10ea756bd3f55d75fbd8890232d907f8d64080449b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2300
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:88a0098a628fe43a9b422f8ebb774086fb65ed389a195e2779482a4a63447e28
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2300
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:8fbdd1ba728058d5f437186b9055ca28596140068ebc69ecff4fa52717b19a82
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2310
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:e438bcacf099a92b143793e88c00c6ac0afb31effe4b0eed49a935c9265ad943
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2310
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:4bba8828e72fd7c9d38c22ba1c2a4f7130817a4e7eac8fb63c13e86465a8e1e7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2312
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:ddaf00914e3a412d21ec3a814e24f3d4cc382b5c4d6c21e9b1b94dde16ddf194
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2312
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:81590ec33b2f00775d3c6596f610887b670de7c0b89148b09eab7584f5b0b0ec
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2320
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:3bbfb6177e4839087f615a01ee54f9e06a95acaddbb083e11851b6af9315dbf0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2320
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:52f337cd5d7d5d199eebf4fc722f8c5279f652506f009efbc0f8f6de88e18718
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2330
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:93168fd8cd4fb32f041795afb8fb0e21cf81081d6cc463a44356e153dc1ad032
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2330
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:b293c1269166cc6181f68b8d803fdfcf20fdbd5df2787ed0453724b22e298fb2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2340
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:1fd99a46758cd29fce846d0d590021758b2a7a3efedb817bb205359caa7d4f67
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2340
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:6f2da9ecd8f5021964d0dfa85144830efcfbd0462d18f18f036971e5f17b3bb6
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2350
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:de82344daa0caeabc6559656da0af285436a687e8f371744c0c51bdbc309167d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2350
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:49f34122ab46ab5d7ead094b6e40817b62c75b6a809f67db07d68bce750da51e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2360
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:ffa0d7cb4068df84319776dbfb66210297da1b8466ccd5451318fc3de79736c3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2360
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:9e1fefc9a94d72a7b5a3f4e2d53ebd23e5ab221df17a5afde42ce973277838f6
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2370
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:b6f61188379def8c796c738549c099bd40bcd9bb44f5c30682c5edd136347aca
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2370
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:5e768aefade6d18cd65cb1eb5ee233844f9f7e7b52631f93a0982b67d382239d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2380
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:719178251893def955e444e706ff07042ea98d294671315d95da504c1f47de24
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2380
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:37ab7354273f4dcd19bad6936f10e92220d98b8c0266002221477a0e2d146c81
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2390
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:da95bff69deb63545d9782ed20cbdd17c1a79c6b16165580bf96a1d5191e6a59
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2390
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:70d4c799c7d905fac27457d63e662ea72bca9e899a692e425609e4eaa45129e6
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2400
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:f2c853ff91809282c04d5b1381ceae366518bf07b16649a61aa6c60c47f10714
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2400
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:a4a0d0453f0761b9e114d0d4cc7c14091a2a9c30790f18ffa6bf1e365d5083fe
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2410
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:f10983c68aff358e285d89d827c27b3487a3ee3b8e121cdaa295bf5fa8501145
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2410
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:decb3932ebb5b848b90a4a23b083f0cb5237eec2844095d8c58a6798da8bb999
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2420
          value: quay.io/arkmq-org/activemq-artemis-broker-init@sha256:3d2bd413d85ecc3bd5fedab18402de029679e3760ed2be7982d37e6b8bcb5b59
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2420
          value: quay.io/arkmq-org/activemq-artemis-broker-kubernetes@sha256:673384959d87408cab9fc92f305dc47b3e7bad3a81b182de104d47f76e7df4e1
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_WEBHOOKS
          value: "false"
        image: quay.io/arkmq-org/activemq-artemis-operator:2.0.6
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8383
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePolicy: FallbackToLogsOnError
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: activemq-artemis-controller-manager
      terminationGracePeriodSeconds: 10
