apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: amq-broker-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        com.company: Red_Hat
        control-plane: controller-manager
        name: amq-broker-operator
        rht.comp: Broker_AMQ
        rht.comp_ver: 7.12.0
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: 2024.Q2
        rht.subcomp: broker-amq-operator
        rht.subcomp_t: application
    spec:
      containers:
      - args:
        - --zap-log-level=info
        - --zap-encoder=console
        - --zap-time-encoding=iso8601
        - --leader-elect
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7110
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b9f93c243ead118651083880786a81c624f390fcc3596c7ec5ebd55f34f95ea3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7110
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:25c3732e945b4bc3e9aca721ce709d0217339b065d9dac9afdb6202e9fd8a799
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7110_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b9f93c243ead118651083880786a81c624f390fcc3596c7ec5ebd55f34f95ea3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7110_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:25c3732e945b4bc3e9aca721ce709d0217339b065d9dac9afdb6202e9fd8a799
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7110_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b9f93c243ead118651083880786a81c624f390fcc3596c7ec5ebd55f34f95ea3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7110_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:25c3732e945b4bc3e9aca721ce709d0217339b065d9dac9afdb6202e9fd8a799
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7111
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9c1ac38bf8eec67a3da57c3cc61105513776a749408cb287fe6448a17889de4e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7111
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:40ccaf2bb2e0f8132f2541b39cb835f17b38050b3ca9232f0861fd5fcaf4324a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7111_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9c1ac38bf8eec67a3da57c3cc61105513776a749408cb287fe6448a17889de4e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7111_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:40ccaf2bb2e0f8132f2541b39cb835f17b38050b3ca9232f0861fd5fcaf4324a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7111_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9c1ac38bf8eec67a3da57c3cc61105513776a749408cb287fe6448a17889de4e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7111_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:40ccaf2bb2e0f8132f2541b39cb835f17b38050b3ca9232f0861fd5fcaf4324a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7112
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:0dde839c2dce7cb684094bf26523c8e16677de03149a0fff468b8c3f106e1f4f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7112
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:29f07006ad62023c20d34971cb3ae900349efae5ab2918aaa8e5647d788032be
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7112_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:0dde839c2dce7cb684094bf26523c8e16677de03149a0fff468b8c3f106e1f4f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7112_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:29f07006ad62023c20d34971cb3ae900349efae5ab2918aaa8e5647d788032be
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7112_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:0dde839c2dce7cb684094bf26523c8e16677de03149a0fff468b8c3f106e1f4f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7112_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:29f07006ad62023c20d34971cb3ae900349efae5ab2918aaa8e5647d788032be
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7113
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5e5d8b551ab8ca377e0bc939037970a2f31ee14e9f555853ebea2759d673895a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7113
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ade37271426ab8f543d72f8da3e9f663d665f9427379a2539fc9323f6897cc44
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7113_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5e5d8b551ab8ca377e0bc939037970a2f31ee14e9f555853ebea2759d673895a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7113_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ade37271426ab8f543d72f8da3e9f663d665f9427379a2539fc9323f6897cc44
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7113_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5e5d8b551ab8ca377e0bc939037970a2f31ee14e9f555853ebea2759d673895a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7113_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ade37271426ab8f543d72f8da3e9f663d665f9427379a2539fc9323f6897cc44
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7114
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8b4c4400a02c6cacfd978147b158e2ccbe5da955578b4b970a5ee7edac865326
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7114
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:89bb769b4c33eb931cc7866eeabec9a315b913851cfa84bc6e11ae8d1e8b2cbb
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7114_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8b4c4400a02c6cacfd978147b158e2ccbe5da955578b4b970a5ee7edac865326
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7114_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:89bb769b4c33eb931cc7866eeabec9a315b913851cfa84bc6e11ae8d1e8b2cbb
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7114_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8b4c4400a02c6cacfd978147b158e2ccbe5da955578b4b970a5ee7edac865326
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7114_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:89bb769b4c33eb931cc7866eeabec9a315b913851cfa84bc6e11ae8d1e8b2cbb
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7115
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5f842ebe9a6a4294a056ad10189a5f277cfd3fb4e6e0b3225e194bd5c131151d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7115
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:7d53744ae8c77aea09c59165486c9ed0eaa131140f6b346042293bce0bd8a745
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7115_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5f842ebe9a6a4294a056ad10189a5f277cfd3fb4e6e0b3225e194bd5c131151d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7115_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:7d53744ae8c77aea09c59165486c9ed0eaa131140f6b346042293bce0bd8a745
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7115_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5f842ebe9a6a4294a056ad10189a5f277cfd3fb4e6e0b3225e194bd5c131151d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7115_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:7d53744ae8c77aea09c59165486c9ed0eaa131140f6b346042293bce0bd8a745
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7116
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:442b6638133d42fa7faa41d86e47be95cdca56c2e16efcd6e7e22991c3812a36
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7116
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:0f443f5aa818dd85bfa93e51e37bdac3909628a283aa52a89125b527dd75d9aa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7116_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:442b6638133d42fa7faa41d86e47be95cdca56c2e16efcd6e7e22991c3812a36
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7116_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:0f443f5aa818dd85bfa93e51e37bdac3909628a283aa52a89125b527dd75d9aa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7116_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:442b6638133d42fa7faa41d86e47be95cdca56c2e16efcd6e7e22991c3812a36
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7116_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:0f443f5aa818dd85bfa93e51e37bdac3909628a283aa52a89125b527dd75d9aa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:227fbe6e428848a0edb8086a00f8d9d993b184392e1f4161febff949ce943cbf
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:3cc58e98c905d427d6be214a8df3c2687170f74abeacc33366f91bfc18e69a3a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:227fbe6e428848a0edb8086a00f8d9d993b184392e1f4161febff949ce943cbf
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:3cc58e98c905d427d6be214a8df3c2687170f74abeacc33366f91bfc18e69a3a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:227fbe6e428848a0edb8086a00f8d9d993b184392e1f4161febff949ce943cbf
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:3cc58e98c905d427d6be214a8df3c2687170f74abeacc33366f91bfc18e69a3a
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_WEBHOOKS
          value: "false"
        image: registry.redhat.io/amq7/amq-broker-rhel8-operator@sha256:757c2f0129a6eadc2e427eb5bb3051b14d1770bc227214924ad4966a7f412a1f
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8383
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: amq-broker-controller-manager
      terminationGracePeriodSeconds: 10
