apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: amq-broker-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        com.company: Red_Hat
        control-plane: controller-manager
        name: amq-broker-operator
        rht.comp: Broker_AMQ
        rht.comp_ver: 7.14.0
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: 2026.Q1
        rht.subcomp: broker-amq-operator
        rht.subcomp_t: application
    spec:
      containers:
      - args:
        - --zap-log-level=info
        - --zap-encoder=console
        - --zap-time-encoding=iso8601
        - --leader-elect
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:40920687402fd747ca02d384e63692a5e1db625723a2bf3056a607c92ee8eee1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:d42d713da0ce6806fdc6492b6342586783e6865a82a8647d3c4288439b1751ee
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:40920687402fd747ca02d384e63692a5e1db625723a2bf3056a607c92ee8eee1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:d42d713da0ce6806fdc6492b6342586783e6865a82a8647d3c4288439b1751ee
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:40920687402fd747ca02d384e63692a5e1db625723a2bf3056a607c92ee8eee1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:d42d713da0ce6806fdc6492b6342586783e6865a82a8647d3c4288439b1751ee
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7121
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b2402179b1d0ff9c950defe5d8808195ef9a4c3e13e3c469cae31ab51d5f5014
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7121
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:47fd4ce2533496828aba37bd1f9715e2164d5c90bd0fc6b25e7e0786d723bf01
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7121_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b2402179b1d0ff9c950defe5d8808195ef9a4c3e13e3c469cae31ab51d5f5014
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7121_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:47fd4ce2533496828aba37bd1f9715e2164d5c90bd0fc6b25e7e0786d723bf01
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7121_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b2402179b1d0ff9c950defe5d8808195ef9a4c3e13e3c469cae31ab51d5f5014
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7121_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:47fd4ce2533496828aba37bd1f9715e2164d5c90bd0fc6b25e7e0786d723bf01
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7122
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:7f9b921d89b6d4d91b365659afff127d99f1455b94b48a10a6a7f4c38dd8b700
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7122
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:dc13871dfed52402c40fd192900fc3cb5a49da4fa08e4ec4d0e23a879e83db25
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7122_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:7f9b921d89b6d4d91b365659afff127d99f1455b94b48a10a6a7f4c38dd8b700
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7122_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:dc13871dfed52402c40fd192900fc3cb5a49da4fa08e4ec4d0e23a879e83db25
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7122_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:7f9b921d89b6d4d91b365659afff127d99f1455b94b48a10a6a7f4c38dd8b700
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7122_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:dc13871dfed52402c40fd192900fc3cb5a49da4fa08e4ec4d0e23a879e83db25
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7123
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9cc48eecf1442ae04b8543fa5d4381a13bc2831390850828834d387006d1342b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7123
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:bb6fbd68475a7852b4d99eea6c4ab313f9267da7963162f0d75375d7063409e7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7123_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9cc48eecf1442ae04b8543fa5d4381a13bc2831390850828834d387006d1342b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7123_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:bb6fbd68475a7852b4d99eea6c4ab313f9267da7963162f0d75375d7063409e7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7123_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9cc48eecf1442ae04b8543fa5d4381a13bc2831390850828834d387006d1342b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7123_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:bb6fbd68475a7852b4d99eea6c4ab313f9267da7963162f0d75375d7063409e7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7124
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:ffffa9875f0379e9373f89f05eb06e5a193273bb04bc3aa5f85b044357b79098
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7124
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:16253895bc113f395dc6ab5cd511901e43b6ee676369ec80d598a8741c3c9bf4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7124_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:ffffa9875f0379e9373f89f05eb06e5a193273bb04bc3aa5f85b044357b79098
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7124_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:16253895bc113f395dc6ab5cd511901e43b6ee676369ec80d598a8741c3c9bf4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7124_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:ffffa9875f0379e9373f89f05eb06e5a193273bb04bc3aa5f85b044357b79098
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7124_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:16253895bc113f395dc6ab5cd511901e43b6ee676369ec80d598a8741c3c9bf4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7125
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:edf6b0d3c54cc780eeaac4bcd196e5520abbeab2203d3aad28f43e22533458ee
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7125
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ba6bb4a1bb630a0582c2cba9b63e6f331d497e2720ad9eeaea08d44cd2daf183
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7125_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:edf6b0d3c54cc780eeaac4bcd196e5520abbeab2203d3aad28f43e22533458ee
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7125_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ba6bb4a1bb630a0582c2cba9b63e6f331d497e2720ad9eeaea08d44cd2daf183
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7125_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:edf6b0d3c54cc780eeaac4bcd196e5520abbeab2203d3aad28f43e22533458ee
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7125_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ba6bb4a1bb630a0582c2cba9b63e6f331d497e2720ad9eeaea08d44cd2daf183
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7130
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:ff80e0a7accda6825bf834d9aec27f48205dd6329991890dd017b4d21d0da5c8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7130
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:755d0f7421efba76f52818bb3a8667cd7d2dcff2c7054dac1a4637b74ecac51d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7130_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:ff80e0a7accda6825bf834d9aec27f48205dd6329991890dd017b4d21d0da5c8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7130_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:755d0f7421efba76f52818bb3a8667cd7d2dcff2c7054dac1a4637b74ecac51d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7130_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:ff80e0a7accda6825bf834d9aec27f48205dd6329991890dd017b4d21d0da5c8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7130_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:755d0f7421efba76f52818bb3a8667cd7d2dcff2c7054dac1a4637b74ecac51d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7131
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:54004a7076fff8787f14e238a7c2dd21884a882097fb474412d96b0138ca9249
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7131
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:c8ccf2fb03e97fcedc3299ada2f63f47beaa7643df4b201fcb30899f923436b9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7131_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:54004a7076fff8787f14e238a7c2dd21884a882097fb474412d96b0138ca9249
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7131_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:c8ccf2fb03e97fcedc3299ada2f63f47beaa7643df4b201fcb30899f923436b9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7131_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:54004a7076fff8787f14e238a7c2dd21884a882097fb474412d96b0138ca9249
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7131_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:c8ccf2fb03e97fcedc3299ada2f63f47beaa7643df4b201fcb30899f923436b9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7132
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:80bca92852d08a7657fb090fe44bfda10baf231c31139a24edec83f542f36232
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7132
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:dd84cb2dfdecd4f5a3fc50a9e167ea6970d1d52d8c7427c201a74a76e151d430
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7132_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:80bca92852d08a7657fb090fe44bfda10baf231c31139a24edec83f542f36232
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7132_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:dd84cb2dfdecd4f5a3fc50a9e167ea6970d1d52d8c7427c201a74a76e151d430
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7132_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:80bca92852d08a7657fb090fe44bfda10baf231c31139a24edec83f542f36232
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7132_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:dd84cb2dfdecd4f5a3fc50a9e167ea6970d1d52d8c7427c201a74a76e151d430
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7133
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:b489a01e70ca8446eb1cd34262679f006f1800501aa7248706ab5ffe94516040
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7133
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:c4642192e7ce50d164c8f7f25e87997d863c4fb0c88858a34ae2797f76163fda
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7133_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:b489a01e70ca8446eb1cd34262679f006f1800501aa7248706ab5ffe94516040
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7133_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:c4642192e7ce50d164c8f7f25e87997d863c4fb0c88858a34ae2797f76163fda
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7133_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:b489a01e70ca8446eb1cd34262679f006f1800501aa7248706ab5ffe94516040
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7133_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:c4642192e7ce50d164c8f7f25e87997d863c4fb0c88858a34ae2797f76163fda
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7140
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:3f69c9739de987878d672427258d5e5831d6acecd091c52577b917f72f781793
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7140
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:576fec4db756074e7f9d0669e07932d015e69cd36bca07c3a69b7252469ebc90
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7140_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:3f69c9739de987878d672427258d5e5831d6acecd091c52577b917f72f781793
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7140_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:576fec4db756074e7f9d0669e07932d015e69cd36bca07c3a69b7252469ebc90
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7140_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel9@sha256:3f69c9739de987878d672427258d5e5831d6acecd091c52577b917f72f781793
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7140_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel9@sha256:576fec4db756074e7f9d0669e07932d015e69cd36bca07c3a69b7252469ebc90
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_WEBHOOKS
          value: "false"
        image: registry.redhat.io/amq7/amq-broker-rhel9-operator@sha256:cf43489c5c49e0e21ebb2e89c51ace56b8af075b38b080f7522b5b36324459d4
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8383
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 384Mi
          requests:
            cpu: 200m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePolicy: FallbackToLogsOnError
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: amq-broker-controller-manager
      terminationGracePeriodSeconds: 10
